In [39]:
using MFA.Ensemble
using Lattices
using LinearAlgebra

In [40]:
ltc = Lattice2D(100, 100, 1)

Lattice2D{Int64}(100, 100, 1)

In [41]:
p = MFAParameters(ltc, [1], [2])

MFAParameters{Lattice2D{Int64}}(Lattice2D{Int64}(100, 100, 1), [1], [2.0], Matrix{Int64}[])

In [42]:
prepare_MFA!(p)

In [82]:
v = zeros(10000);
v[1] = 1
v = normalize(v)

10000-element Vector{Float64}:
 1.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [83]:
gipr, _ = compute_gipr_2(p, v)

([1.0;;], [0.0;;])

In [84]:
gipr

1×1 Matrix{Float64}:
 1.0

In [85]:
v = ones(10000);
v = normalize(v)

10000-element Vector{Float64}:
 0.01
 0.01
 0.01
 0.01
 0.01
 0.01
 0.01
 0.01
 0.01
 0.01
 0.01
 0.01
 0.01
 ⋮
 0.01
 0.01
 0.01
 0.01
 0.01
 0.01
 0.01
 0.01
 0.01
 0.01
 0.01
 0.01

In [86]:
gipr, _ = compute_gipr_2(p, v)

([9.999999999998701e-5;;], [-0.000921034037197621;;])

In [87]:
gipr

1×1 Matrix{Float64}:
 9.999999999998701e-5